version: '3'
services: 
  rabbitmq:
        image: rabbitmq:latest
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
  publisher: 
    build: ./publisher
    ports: 
      - "4201:4201"
  consumer: 
    build: ./consumer
    ports: 
      - "4202:4202"
            