version: '3'
services: 
  consumer: 
    build: ./consumer
    ports: 
      - "4200:4200"
  publisher: 
    build: ./publisher
    ports: 
      - "4201:4201"
  rabbitmq: 
    build: ./rabbitmq
    ports: 
      - "5672:5672" 
    restart: always 