apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-test
  region: us-west-2
nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh: 
      publicKeyName: eks-ivan-test-key
