apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-messages-api
  labels:
    app: k8s-messages-api
  namespace: default
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: k8s-messages-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-messages-api
    spec:
      containers:
      - image: {{ .Values.api.image }}:{{ .Values.version }}
        imagePullPolicy: Always
        name: k8s-messages-api
        ports:
        - containerPort: 4201
          protocol: TCP
        env:
        - name: RABBITMQ
          value: "http://rabbitmq.default.svc.cluster.local/"