apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-messages-rabbitmq
  labels:
    app: k8s-messages-rabbitmq
  namespace: default
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: k8s-messages-rabbitmq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-messages-rabbitmq
    spec:
      containers:
      - image: {{ .Values.rabbitmq.image }}:{{ .Values.version }}
        imagePullPolicy: Always
        name: k8s-messages-rabbitmq
        ports:
        - containerPort: 4369
        - containerPort: 5672
        - containerPort: 25672
        - containerPort: 15672
          protocol: TCP