apiVersion: v1
kind: Service
metadata:
  name: core-org-config
spec:
  selector:
    app: core-org-config
  type: NodePort
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000