apiVersion: v1
kind: Service
metadata:
  name: k8s-messages-rabbitmq
spec:
  selector:
    app: k8s-messages-rabbitmq
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 5672
      targetPort: 5672