apiVersion: v1
kind: Pod
metadata:
  name: pod-consumer
  labels:
    component: node-app
spec:
  containers:
    - name: consumer
      image: kat1330/docker-solution-worker
      ports:
        - containerPort: 3000