apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-ivan-test
  region: us-west-2
nodeGroups:
  - name: node-1
    instanceType: t2.small
    desiredCapacity: 1
    ssh:
      publicKeyName: eks-ivan-keypair
