apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-ivan-test
  region: us-west-2
nodeGroups:
  - name: node-1
    instanceType: t2.small
    desiredCapacity: 1
    ssh:
      publicKeyName: eks-ivan-keypair
  # - name: node-2
  #   minSize: 3
  #   maxSize: 5
  #   instanceDistribution:
  #     maxPrice: 0.2
  #     instanceType: ["t2.small", "t3.small"]
  #     onDemandBaseCapacity: 0
  #     onDemandPercentageAboveBaseCapacity: 50
  #   ssh:
  #     publicKeyName: eks-ivan-keypair
